### PR TITLE
Fix build with Boost 1.69

### PR DESCRIPTION
**Pull request by denpamusic**
This fixes build failing when building with Boost 1.69 (specifically on ArchLinux).
```
src/cryptonote_basic/miner.cpp:640:25: error: assigning to 'bool' from incompatible type 'boost::logic::tribool'
          on_ac_power = !battery_powered;
                        ^~~~~~~~~~~~~~~~
```
See:
https://github.com/monero-project/monero/pull/4700

### CODE REVIEW

**Comment by denpamusic** [comment]
Redid using `static_cast<bool>` and verified that everything still builds fine.
My C++ spirit has been long outdated so I'll take your word for it:)

Sorry about wrong branch, didn't find contributing guidelines, so wasn't sure where to put it.

**Comment by atanmarko** [comment]
Thanks, contributing guidelines are long time on a TODO list... :(
